version: "3.7"
services:
  front:
    build:
      context: ./frontend
    ports:
      - "3000:3000"

  statistics:
    build:
      context: ./statistics
    depends_on:
      - kafka-init
    ports:
      - "8080:8080"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    environment:
      SETUP_VERSION: "dockerTest"

  redis:
    image: "redis:alpine"

  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
      
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    ports:
      - "29092:29092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092,PLAINTEXT_INTERNAL://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  kafka-init:
    build:
      context: ./kafka/init
    container_name: kafka-init
    depends_on:
      - kafka
