version: "3.7"
services:
  front:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
  statistics:
    build:
      context: ./statistics
    ports:
      - "8080:8080"
    ulimits:
      nofile:
        soft: "65536"
        hard: "65536"
    environment:
      SETUP_VERSION: "dockerTest"
  redis:
    image: "redis:alpine"
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"

